# Generated by Django 5.1.4 on 2025-02-08 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_payment_vnpay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment_vnpay',
            name='order_id',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
    ]
