# Generated by Django 5.1.4 on 2025-12-04 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('processing', 'Đang xử lý'), ('shipping', 'Đang giao'), ('completed', 'Hoàn thành')], default='processing', max_length=20),
        ),
    ]
