# Generated by Django 5.1.4 on 2025-12-04 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('processing', 'Đang xử lý'), ('shipping', 'Đang giao'), ('delivered', 'Đã giao'), ('completed', 'Hoàn thành')], default='processing', max_length=20),
        ),
    ]
